feat: basic support for inferrable types
vega/ts-json-schema-generator pull request #1407
Opened 2022-09-15 14:50 UTC by swnf

This PR adds basic support to infer the type of properties without an explicit type (see #1406). For example:
```ts
export class Foo {
  a = false;
}
```
Previously, properties without an explicit type were always ignored. With this PR they will get their correct type, _unless they are initialized with a function call or a property access_. In this case they will be ignored.

I created a small helper method to create the `BaseType` instead of using the `childNodeParser` because I think it makes sense the node parser is only for "type AST".

2022-09-16 13:30 UTC, arthurfiorette requested changes
Hey @swnf, I'm not dedicated to this project or either a main contributor. But I arrieved at your PR randomly and decided to stick my nose for a bit, you can only use what you find useful :)

2022-09-16 13:30 UTC, arthurfiorette commented on test/valid-data/class-single/main.ts
> +    public constructor(protected a: number, private b: number, c: number, public propC = 42,
You could add a comment to help identify that the `= 42` is used to test inferrable types.

2022-09-16 13:30 UTC, arthurfiorette commented on src/Utils/inferrableType.ts
> +    else return undefined;
This seems more readable :)

```suggestion
  if (expression == undefined) {
    return undefined;
  }

  if (ts.isParenthesizedExpression(expression)) {
    return getInferrableType(expression.expression);
  }

  if (
    ts.isNumericLiteral(expression) ||
    (ts.isPrefixUnaryExpression(expression) &&
      (expression.operator === ts.SyntaxKind.PlusPlusToken ||
        expression.operator === ts.SyntaxKind.MinusMinusToken ||
        expression.operator === ts.SyntaxKind.PlusToken ||
        expression.operator === ts.SyntaxKind.MinusToken ||
        expression.operator === ts.SyntaxKind.TildeToken))
  ) {
    return new NumberType();
  }

  if (
    ts.isStringLiteral(expression) ||
    ts.isNoSubstitutionTemplateLiteral(expression) ||
    ts.isTemplateLiteral(expression)
  ) {
    return new StringType();
  }

  if (
    expression.kind === ts.SyntaxKind.FalseKeyword ||
    expression.kind === ts.SyntaxKind.TrueKeyword ||
    (ts.isPrefixUnaryExpression(expression) && expression.operator === ts.SyntaxKind.ExclamationToken)
  ) {
    return new BooleanType();
  }

  if (expression.kind === ts.SyntaxKind.NullKeyword) {
    return new NullType();
  }

  if (expression.kind === ts.SyntaxKind.UndefinedKeyword || ts.isVoidExpression(expression)) {
    return new UndefinedType();
  }
  
  return undefined;
```

2022-09-16 13:30 UTC, arthurfiorette commented on src/Utils/inferrableType.ts
> +    // TODO: Ideally, this should also support function calls and property access expressions
About function calls (a.k.a inferred response types), you'll need to use the typechecker to get the inferred type from a function. Probably like what I've done with kitajs:

https://github.com/arthurfiorette/kita/blob/48dc243d7e3f10363b33c135e758003de1912b83/packages/generator/src/util/node.ts#L41

The only problem is that sometimes functions return types are not manually typed, and when you do the above, it's generated ts.TypeNodes without a valid source. The good news is that the #1386 fixed it.

For property access expressions, I guess that it is also going to be similar to function response types.

2022-09-16 13:30 UTC, arthurfiorette commented on src/NodeParser/InterfaceAndClassNodeParser.ts
> +                    (member.type || getInferrableType(member.initializer)) &&
Could you do something so we don't call `getInferrableType` inside the `filter` and the `map` function?

2022-09-17 13:08 UTC, swnf commented
Thanks for your feedback @arthurfiorette, I made some changes based on it. However, I'm not so sure anymore if my approach makes sense. There does not seem to be any advantage of parsing the AST of the initializer (except maybe for an `AsExpression`). It might make more sense to just use the type checker directly to get the type of a member if it has no explicit type (would probably depend on #1386).

2022-10-16 13:59 UTC, domoritz commented
Thanks for the pull request. I think using the type checker directly would make sense if it makes the code a lot simpler. We mainly use the AST to preserve aliases but that isn't an issue here with inferred types.

2022-10-16 13:59 UTC, domoritz commented
@swnf would you be able to revise this pull request?

2022-10-16 14:21 UTC, swnf commented
Yes, I think I can update it next week.

2022-10-17 10:27 UTC, swnf commented
I've updated my code. It now uses the type checker and works for all types. I will rebase the PR once #1386 is merged.

2022-10-17 13:06 UTC, domoritz commented
I merged https://github.com/vega/ts-json-schema-generator/pull/1386

2022-10-17 13:20 UTC, swnf commented
I've rebased the PR. I think it is now ready for review.

2022-11-25 09:10 UTC, swnf commented
@domoritz can you have a look at this PR? It would help me with some eslint issues.

2022-12-03 02:51 UTC, merged