Error "has multiple definitions" with discriminate unions
vega/ts-json-schema-generator pull request #1836
Opened 2023-12-20 15:49 UTC by webjunkie

I encounter errors with using discriminate unions in certain cases. I was able to reproduce a test case that throws `Type "Animal" has multiple definitions.`

Interestingly, if I modify the example and add just another type and make that the discriminate union, it works, but it would be very inconvenient in my project:

```ts
export type Fish = {
    animal_type: "fish";
    found_in: "ocean" | "river";
};

export type Bird = {
    animal_type: "bird";
    can_fly: boolean;
    likes_to_eat: EatSource;
};

export type Animal = Bird | Fish;

/**
 * @discriminator animal_type
 */
export type EatSource = Animal
```

2025-12-02 18:13 UTC, domoritz commented
@arthurfiorette can you take a look?

2025-12-02 19:55 UTC, arthurfiorette requested changes
impl makes sense ihmo. Needs to fix lint issues before merging

2026-01-28 09:33 UTC, webjunkie commented
Lint should be fixed btw

2026-01-29 13:51 UTC, arthurfiorette approved these changes

2026-01-29 13:51 UTC, merged