Configurable formatter
vega/ts-json-schema-generator pull request #565
Opened 2020-11-09 10:49 UTC by fwal

Hi! 👋 

This is a proposal on how to enable customisation of the formatting step by adding the ability to add additional formatters programatically. In the example included in the test, a function type is formatted as a custom object defined by the consumer.

Example:
```ts
createFormatter(configuration, (formatter) => {
    formatter.addTypeFormatter(new MyFunctionTypeFormatter())
})
```

I'm looking forward to your feedback!

2020-11-09 20:04 UTC, domoritz approved these changes
This is awesome. Just one comment about naming. 

Can you also add documentation and maybe an example to the readme?

2020-11-09 20:04 UTC, domoritz commented on factory/formatter.ts
> +export function createFormatter(config: Config, configurator?: FormatterConfigurator): TypeFormatter {
Can you come up with a name for configurator that is easier to understand for someone who is new to the API?

2020-11-10 15:18 UTC, fwal commented
I've added an example but having a bit of struggle with the naming of the configuration function (naming is one of the hardest parts with programming after all 😄) so I'll have to get back to you on that.

2020-11-10 15:26 UTC, domoritz commented
Thank you for the docs. Yes, naming is hard. Maybe `augment`, `augmentor`?

2020-11-10 15:55 UTC, fwal commented
Yeah that works, changed to `FormatterAugmentor`.

2020-11-10 16:01 UTC, domoritz requested changes

2020-11-10 16:01 UTC, domoritz commented on README.md
> +2. Then we add the formatter as a child to the core formatter using the configuration callback:
```suggestion
2. Then we add the formatter as a child to the core formatter using the augmentation callback:
```

2020-11-10 16:01 UTC, domoritz commented on factory/formatter.ts
> +export function createFormatter(config: Config, configurator?: FormatterAugmentor): TypeFormatter {
```suggestion
export function createFormatter(config: Config, augmentor?: FormatterAugmentor): TypeFormatter {
```

2020-11-10 16:01 UTC, domoritz commented on factory/formatter.ts
> +        configurator(chainTypeFormatter);
```suggestion
    if (augmentor) {
        augmentor(chainTypeFormatter);
```

2020-11-10 16:02 UTC, domoritz commented on factory/formatter.ts
> +export function createFormatter(config: Config, configurator?: FormatterAugmentor): TypeFormatter {
or `formatterAugmentor` like below

2020-11-10 16:35 UTC, domoritz approved these changes

2020-11-10 16:35 UTC, domoritz commented on test/config.test.ts
> +    formatterAugmentor?: FormatterAugmentor
Last nit: make the parameter name consistent across the whole repo.

2020-11-10 16:40 UTC, domoritz requested changes

2020-11-10 16:40 UTC, domoritz commented on test/config.test.ts
> +    formatterAugmentor?: FormatterAugmentor
```suggestion
    augmentor?: FormatterAugmentor
```

2020-11-10 16:40 UTC, domoritz commented on test/config.test.ts
> +            createFormatter(config, formatterAugmentor),
```suggestion
            createFormatter(config, augmentor),
```

2020-11-10 16:51 UTC, merged